CRM/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index, to_crm
from personalarea.views import lk
from CRM.views import StudentList, StudentDetail, UpdateProfileAdmin, show_students, Create_group, Add_lesson, \
    add_payment, Payments_List, Groups_List, Group_Detail
from personalarea.views import success_page

urlpatterns = [
    path('<int:pk>/', StudentDetail.as_view(), name='std_detail'),
    path('students/', StudentList.as_view(), name='std_list'),
    path('edit/<int:pk>', UpdateProfileAdmin.as_view(), name='edit_a'),
    path('edit/success', success_page, name='success'),
    path('group<int:group_name>/', show_students, name='group_list'),
    path('create_group/', Create_group.as_view(), name='create_group'),
    path('add/', Add_lesson.as_view(), name='add_lesson'),
    path('add_payment/', add_payment, name='add_payment'),
    path('payment_list/', Payments_List.as_view(), name='payment_list'),
    path('group_list/', Groups_List.as_view(), name='gr_list'),
    path('groups_detail<int:pk>/', Group_Detail.as_view(), name='gr_detail'),

]

schedule/urls.py
from django.urls import path

from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth.views import auth_logout, LoginView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView
from django.urls import path, include, reverse_lazy

import schedule.views
from main.decorators import check_recaptcha
from main.views import index, to_crm, register, logout_from
from personalarea.views import lk

urlpatterns = [
    path('', schedule.views.schedule, name='schedule'),
]

school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, \
    PasswordResetCompleteView
from django.urls import path, include, reverse_lazy

import main.views
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
from main.models import Student_on_lesson
from main.serializers import Student_Serializer


class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Student_on_lesson
        fields = ['users']


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = Student_on_lesson.objects.all()
    serializer_class = Student_Serializer


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('scadm/', admin.site.urls),
    path('', include('main.urls')),
    path('lk/', include('personalarea.urls'), name='lk'),
    path('CRM/', include('CRM.urls'), name='CRM'),
    path('schedule/', include('schedule.urls')),
    path('reset/', PasswordResetView.as_view(template_name='registration/pass_reset.html',
                                             success_url=reverse_lazy('password_reset_done')), name='reset'),
    path('reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_done/',
         PasswordResetDoneView.as_view(template_name='registration/pass_reset_done.html'), name='password_reset_done'),
    path('password_complete/',
         PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User
from django.db.models import DateTimeField
from django.urls import reverse_lazy


class Student(User):
    age = models.PositiveIntegerField(null=True)
    payment = models.BooleanField(default=False)
    subs = models.ForeignKey('TypeSubscribe', on_delete=models.SET_NULL, null=True)
    balance = models.IntegerField(default=0, blank=True)

    def __str__(self):
        return self.last_name

    def update_balance(self):
        if self.balance > 0:
            self.payment = True
            self.save()
        else:
            self.payment = False
            self.save()

    class Meta:
        verbose_name = 'Ученик'
        verbose_name_plural = 'Ученики'


class Student_Group(models.Model):
    group_name = models.CharField(max_length=50, blank=False)
    students = models.ManyToManyField(Student, related_name="students")

    def __str__(self):
        return self.group_name

    def get_absolute_url(self):
        return reverse_lazy('CRM')


class TypeSubscribe(models.Model):
    types = models.CharField(max_length=30)

    def __str__(self):
        return self.types

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'


class Contacts(models.Model):
    phone = models.IntegerField()
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name + ' ' + str(self.phone)


class Student_on_lesson(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    student = models.ManyToManyField(Student)

    def __str__(self):
        return str(self.date) + ' ' + str(self.student.name)

schedule/models.py
import calendar

from django.db import models
from main.models import Student, Student_Group


class Days_Lesson(models.Model):
    """ Base model for create lesson """
    time_choices = [
        ('8:30', '8:30'),
        ('10:00', '10:00'),
        ('11:30', '11:30'),
        ('13:00', '13:00'),
        ('14:30', '14:30'),
        ('16:00', '16:00'),
        ('17:30', '17:30')
    ]
    day_choices = [
        ('Понедельник', 'Понедельник'),
        ('Вторник', 'Вторник'),
        ('Среда', 'Среда'),
        ('Четверг', 'Четверг'),
        ('Пятница', 'Пятница'),
        ('Суббота', 'Суббота'),
        ('Воскресенье', 'Воскресенье'),
    ]
    day = models.CharField(
        max_length=15,
        choices=day_choices,
        default='1'
    )
    time = models.CharField(
        max_length=6,
        choices=time_choices,
        default='1'
    )
    group_id = models.ForeignKey(
        Student_Group,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('CRM')

    def __str__(self):
        return self.day + ' ' + self.time

schedule/views.py
from django.shortcuts import render
from django.views.generic import ListView

from main.models import Student
from schedule.models import Days_Lesson, Student_Group


# Create your views here.

def schedule(request):
    day_info = Days_Lesson.objects.all()
    student_info = Student.objects.all()
    context = {'day': day_info, 'student': student_info}
    return render(request, 'schedule.html', context)


def index_1(request):
    return render(request, 'trash/intro.html')

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/aos@2.3.1/dist/aos.css">
    <title>KidsTechSchool</title>
</head>
<body>
<header class="header">
    <div class="wrapper">
        <div class="header_wrapper">
            <div class="header_logo" data-aos="zoom-in">
                <a href="/" class="header_logo-link">
                    <img src="../static/img/logo.svg" alt="logo" class="header_log-link" width="40" height="40">
                    KIDS TECH SCHOOL
                </a>
            </div>
            <nav class="header-nav">
                {% if not user.is_authenticated %}
                    <ul class="header_list">
                    <li class="header-item">
                        <a href="{% url 'register' %}" class="header-link">Registration</a>
                    </li>
                    <li class="header-item">
                        <a href="{% url 'login' %}" class="header-link">Login</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated and not user.is_superuser %}
                    <li class="header-item">
                        <a href="{% url 'lk' %}"
                           class="header-link">Profile {{ user.first_name }} {{ user.last_name }}</a>
                    </li>
                    <li class="header-item">
                        <a href="{% url 'logout' %}" class="header-link">Logout</a>
                    </li>
                {% endif %}
                {% if user.is_superuser %}
                    <li class="header-item">
                        <a href="{% url 'CRM' %}" class="header-link">CRM</a>
                    <li class="header-item">
                        <a href="{% url 'logout' %}" class="header-link">Logout</a>
                    </li>
                    </li>
                {% endif %}
                </ul>
            </nav>
        </div>
    </div>
</header>
<main class="main">
    <section class="intro">
        {% block main %}
        {% endblock %}
    </section>
</main>
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script src="{% static 'js/script_1.js' %}"></script>
</body>
<footer>
    <div class="devops">
        <p class="who_dev">Development by Alekseev © 2021</p>
    </div>
    <div class="my_git">
        <a href="https://github.com/physrow"><img src="/static/img/git_64.png" alt="github.com/physrow"
                                                  width="40"
                                                  height="40"></a>
    </div>

</footer>
</html>

templates/base_2.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style_test.css' %}">
    <title>KidsTechSchool</title>
</head>
<body>
<header>
    <div class="header">
        <div class="header_wrapper">
            asd
        </div>
    </div>
</header>
{% block main %}

{% endblock %}
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>НеШкола</title>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/card.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/contact_form.css">
    <link rel="stylesheet" href="/static/css/social.css">
</head>

<body>
<div class="navbar">
    <div class="logo">
        <a href="{% url 'mainpage' %}">
            NeSchool
        </a>
    </div>
    <div class="menu">
        <ul>
            {% if not user.is_authenticated %}
            <li class="list active">
                <a href="{% url 'mainpage' %}">
                            <span class="icon">
                                <ion-icon name="chatbox-ellipses-outline"></ion-icon>
                            </span>
                    <span class="text">Contact</span>
                    <a>Contact</a>
                </a>
            </li>
            {% endif %}
            {% if user.is_authenticated %}
            <li class="list">
                <a href="{% url 'lk' %}">
                            <span class="icon">
                                <ion-icon name="person-outline"></ion-icon>
                            </span>
                    <span class="text">Profile</span>
                    <a>Profile</a>
                </a>
            </li>
            {% endif %}
            <li class="list">
                {% if  user.is_authenticated %}<a href="{% url 'logout' %}"> {% endif %}
                {% if not user.is_authenticated %}<a href="{% url 'login' %}"> {% endif %}
                            <span class="icon">
                                <ion-icon name="person-add-outline"></ion-icon>
                            </span>
                    <span class="text">SignUp</span>
                </a>
                {% if not user.is_authenticated %}<a>Login</a> {% else %} <a>Logout</a>{% endif %}
            </li>
            <div class="indicator"></div>
        </ul>
    </div>
</div>
<div class="main">
    <div id="particles-js"></div> <!--Flying huinyshki -->
    <div class="overlay">
        <div class="content-area">
            <nav class="social">
                <ul>
                    <li><a href="https://twitter.com">Twitter <i class="fa fa-twitter"></i></a></li>
                    <li><a href="https://github.com">Github <i class="fa fa-github"></i></a></li>
                    <li><a href="https://instagram.com">Instagram <i class="fa fa-instagram"></i></a></li>
                </ul>
            </nav>
            {% block main %}
                {% if not user.is_authenticated %}
                <div class="contact-form">
                    <div class="container">
                        <div class="screen">
                            <div class="screen-header">
                                <div class="screen-header-left">
                                    <div class="screen-header-button close"></div>
                                    <div class="screen-header-button maximize"></div>
                                    <div class="screen-header-button minimize"></div>
                                </div>
                                <div class="screen-header-right">
                                    <div class="screen-header-ellipsis"></div>
                                    <div class="screen-header-ellipsis"></div>
                                    <div class="screen-header-ellipsis"></div>
                                </div>
                            </div>
                            <div class="wrp">
                                <div class="screen-body">
                                    <div class="screen-body-item">
                                        <div class="app-title">
                                            <span>Оставьте заявку на пробное занятие и мы вам перезвоним</span>
                                        </div>
                                        <div class="app-contact">Или напишите нам в Telegram/WhatsApp +79094572061</div>

                                    </div>
                                    <form method="post">
                                        {% csrf_token %}
                                        <div class="screen-body-item">
                                            <div class="app-form">
                                                <div class="app-form-group">
                                                    <input type="text" name="name" class="app-form-control"
                                                           placeholder="Имя">
                                                </div>
                                                <div class="app-form-group">
                                                    <input type="number" name="phone" class="app-form-control"
                                                           placeholder="Номер телефона">
                                                </div>
                                                <div class="app-form-group buttons">
                                                    <input type="submit" class="app-form-button">
                                                </div>
                                            </div>

                                        </div>
                                    </form>
                                </div>
                                <a href="" id="about"></a>
                                <div class="containerrr">
                                    <div class="card">
                                        <div class="box">
                                            <div class="content">
                                                <h3>Junior</h3>
                                                <p>Подписка на 12 занятий в месяц. Занятия проходят в группах,
                                                    максимальная
                                                    количество
                                                    человек в
                                                    группе - 3</p>
                                                <a href="#">Записаться</a>
                                                <p class="card_price">Цена: 4000 р</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>
                {% endif %}
            {% endblock %}
        </div>
    </div>
</div>


<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
<script type="text/javascript" src="/static/js/particles.js"></script>
<script type="text/javascript" src="/static/js/app.js"></script>
<script type="text/javascript" src="/static/js/main.js"></script>
</body>
</html>

templates/index_1.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>KidsTechSchool</title>
</head>
<body>
<header class="header">
    <div class="wrapper">
        <div class="header_wrapper">
            <div class="header_logo">
                <a href="/" class="header_logo-link">
                    <img src="../static/img/logo.svg" alt="logo" class="header_log-link" width="40" height="40">
                </a>
            </div>
            <nav class="header-nav">
                <ul class="header_list">
                    <li class="header-item">
                        <a href="#" class="header-link">About us</a>
                    </li>
                    <li class="header-item">
                        <a href="#" class="header-link">Home</a>
                    </li>
                    <li class="header-item">
                        <a href="#" class="header-link">Contact us</a>
                    </li>
                    <li class="header-item">
                        <a href="{% url 'login' %}" class="header-link">Log in</a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</header>
<main class="main">
    <section class="intro">
        <div class="wrapper">
            <h1 class="intro_title"> Study with us</h1>
            <p class="intro_subtitle">
                We are a young and ambitious school that prepares young programmers. Our program is aimed at quickly
                learning the basics of programming for the transition to applied applications.
            </p>
            <p class="form_title">If u want to join us, fill out the form:</p>
            <form class="join-form">
                <fieldset class="join-form_wrap">
                    <p class="join-form_info">
                        <input type="number" name="phone_form" class="field_1" placeholder="Enter phone">
                        <input type="text" name="name_form" class="field_1" placeholder="Enter name">
                        <button type="submit" class="join-form_submit">join</button>
                    </p>
                </fieldset>
            </form>
        </div>
    </section>
</main>
</body>
</html>

templates/register.html
{% extends 'index.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block main %}
    <div class="card_register">
        <div class="card-body">
            <h4 class="card-title">Register account</h4>
            <form method="post">
                {% csrf_token %}
                <div class="reg_form_view">
                    <p><input class="input_1" type="text" name="username" maxlength="150" required="" id="id_username" placeholder="Логин"></p>
                    <p><input class="input_1" type="text" name="last_name" maxlength="150" id="id_last_name" placeholder="Фамилия"></p>
                    <p><input class="input_1"  type="text" name="first_name" maxlength="150" id="id_first_name" placeholder="Имя"></p>
                    <p><input class="input_1" type="number" name="age" required="" id="id_age" placeholder="Возраст"></p>
                    <p><input class="input_1" type="email" name="email" maxlength="254"
                           id="id_email" placeholder="email"></p>
                   <p> <input class="input_1" type="password" name="password_1" maxlength="20"
                           minlength="6" required="" id="id_password_1" placeholder="Пароль"></p>
                   <p> <input class="input_1" type="password" name="password_2" maxlength="20"
                           minlength="6" required="" id="id_password_2" placeholder="Подтвердите пароль"></p>
                    <script src='https://www.google.com/recaptcha/api.js'></script>
                    <div class="form-group g-recaptcha" data-sitekey="6LfBMSgcAAAAAFq5Ctxc2Ep8K1STmdfBaP6ZFbfY"></div>
                    <input type="submit" class="btn-log" value="Register">
                    {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
{% endblock %}